version: '3'
services:
  db:
    image: postgres:9.6
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=event_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - 5433:5432
